[book]
authors = ["pspiagicw"]
language = "en"
multilingual = false
src = "src"
title = "groom"

[output.html]
default-theme = "ayu"
# additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
